version: '2.1'
services:
  hs_hub:
    image: hs_hub:latest
    volumes:
      - .:/home/node/app/
      - /home/node/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    networks:
      - internal
      - hacker_suite
    env_file: .env

# The volume for the database is persistent across launches
volumes:
  db_store:

# The network allows multiple containers to connect together
networks:
  # internal network for hs_hub services
  internal:
    driver: bridge
    name: internal
  # external network for consumer-facing hacker suite services
  hacker_suite:
    external:
      name: hacker_suite
